language: generic
sudo: required
services:
- docker
env:
  matrix:
  - COMPILER=g++-6 BUILDTYPE=debug
  - COMPILER=g++-6 BUILDTYPE=release BUILD_DOCS=yes
  - COMPILER=clang++-3.8 BUILDTYPE=debug
  - COMPILER=clang++-3.8 BUILDTYPE=release
before_install:
- openssl aes-256-cbc -K $encrypted_49a800b0cce8_key -iv $encrypted_49a800b0cce8_iv
  -in ci/travis.enc -out ci/ssh/travis -d
- docker build -t attugit/xcode -f ci/testing.docker .
script:
- mkdir -p logs
- docker run --env=CXX=$COMPILER --env=BUILDTYPE=$BUILDTYPE --volume=$PWD/logs:/root/xcode/logs --user=root --workdir=/root/xcode attugit/xcode /bin/bash -c "bash ./ci/run.sh"
- |
  if [ ! -z  "${BUILD_DOCS}" ]; then
    docker run --volume=$PWD/ci/ssh:/root/.ssh --volume=$PWD/logs:/logs attugit/xcode /bin/bash -c "bash /root/xcode/ci/deploy.sh"
  fi
